-- V9: 新增仓储风险处置账册

CREATE TABLE IF NOT EXISTS storage_risk_action (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tea_id BIGINT NOT NULL,
    suitability_id BIGINT,
    storage_record_id BIGINT,
    risk_type VARCHAR(50) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    risk_description VARCHAR(500),
    temperature_before DECIMAL(5, 2),
    humidity_before DECIMAL(5, 2),
    seal_before VARCHAR(50),
    action_type VARCHAR(100),
    action_description VARCHAR(1000),
    action_by VARCHAR(100),
    action_date DATETIME,
    temperature_after DECIMAL(5, 2),
    humidity_after DECIMAL(5, 2),
    seal_after VARCHAR(50),
    result_status VARCHAR(20),
    result_description VARCHAR(500),
    follow_up_date DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_risk_tea_id (tea_id),
    INDEX idx_risk_suitability_id (suitability_id),
    INDEX idx_risk_storage_record_id (storage_record_id),
    INDEX idx_risk_level (risk_level),
    INDEX idx_risk_result_status (result_status),
    INDEX idx_risk_created_at (created_at),
    CONSTRAINT fk_risk_tea FOREIGN KEY (tea_id) REFERENCES tea(id) ON DELETE CASCADE,
    CONSTRAINT fk_risk_suitability FOREIGN KEY (suitability_id) REFERENCES storage_suitability(id) ON DELETE SET NULL,
    CONSTRAINT fk_risk_storage_record FOREIGN KEY (storage_record_id) REFERENCES storage_record(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
